# Generated by Django 5.0.7 on 2024-08-25 20:36

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('uuid', models.UUIDField(default=uuid.UUID('8368ae73-19de-45f2-93f1-9bfed29d29ea'), editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=django.utils.timezone.now)),
                ('updated_at', models.DateField(default=django.utils.timezone.now)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('profile_picture', models.ImageField(blank=True, upload_to='profile_picture/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
