# Generated by Django 5.0.7 on 2024-07-27 03:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sharelink', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='temp_media/')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('link', 'Link')], max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=255)),
                ('uploader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploader', to='user.customuser')),
            ],
        ),
    ]
