# Generated by Django 5.0.7 on 2024-07-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_tempmedia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='uploader',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
