# Generated by Django 5.0.7 on 2024-07-27 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_media_uploader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='uploader',
        ),
        migrations.RemoveField(
            model_name='tempmedia',
            name='uploader',
        ),
    ]
