# Generated by Django 5.0.7 on 2024-07-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_media_uploader_remove_tempmedia_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmedia',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
