# Generated by Django 5.0.7 on 2024-07-27 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_tempmedia_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempmedia',
            name='album',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='user.album'),
        ),
    ]
