# Generated by Django 5.0.7 on 2024-07-28 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_notification_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='tempmedia',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
