# Generated by Django 5.0.7 on 2024-07-29 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_album_updated_at_alter_media_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='created_at',
        ),
    ]
